{
 "title": "VO - Kafka Connect Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "connector",
    "query": "label_values(kafka_connect_connector_state_running,connector)"
   }
  ]
 },
 "panels": [
  {
   "title": "Gauge count",
   "type": "graph",
   "description": "# HELP kafka_connect_connectors_count number of deployed connectors\n# TYPE kafka_connect_connectors_count gauge",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connectors_count",
     "legendFormat": "kafka_connect_connector_state_running is the connector running?"
    }
   ]
  },
  {
   "title": "Kafka connect up",
   "type": "graph",
   "description": "kafka_connect_up was the last scrape of kafka connect successful?",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_connect_up" }
   ]
  },
  {
   "title": "Connector {{$connector}} status",
   "type": "graph",
   "description": "# HELP kafka_connect_connector_state_running is the connector running?\n# TYPE kafka_connect_connector_state_running gauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_state_running{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Kafka connector state",
   "type": "graph",
   "description": "# HELP kafka_connect_connector_tasks_state the state of tasks. 0-failed, 1-running, 2-unassigned, 3-paused\n# TYPE kafka_connect_connector_tasks_state gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_tasks_state{connector=~\"$connector\"}",
     "legendFormat": "kafka_connect_connector_tasks_state the state of tasks. 0-failed, 1-running, 2-unassigned, 3-paused"
    }
   ]
  }
 ]
}