{
 "title": "VO - General dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "nsexporters", "label": "Namespace Exporters", "query": { "query": "label_values(zk_up, namespace)" } }
  ]
 },
 "panels": [
  { "title": "Cluster nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "Disk Pressure"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "Memory Pressure"
    }
   ]
  },
  {
   "title": "Ready Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\", prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"} == 1",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"} == 1",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Resources and utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:node_cpu:ratio{job=\"node-exporter\"}*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n  node_memory_MemAvailable_bytes{job=\"node-exporter\"}\n/\n  node_memory_MemTotal_bytes{job=\"node-exporter\"}\n* 100\n) "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n(1 -\n(\n  max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"rootfs\"})\n/\n  max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"rootfs\"})\n))*100"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pods status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"} == 1)",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"} == 1)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Failed Pods ",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Failed\"} == 1",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pending Pods ",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Pending\"} == 1",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",namespace=~\".*\"} > 0"
    },
    {
     "expr": "rate(kube_pod_container_status_restarts_total{job=\"kube-state-metrics\",namespace=~\".*\"}[30m]) * 60 * 5 > 0"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "MongoDB Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{namespace=\"$nsexporters\"}"
    }
   ]
  },
  {
   "title": "Kafka Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kminion_kafka_cluster_info{namespace=\"$nsexporters\"}"
    }
   ]
  },
  {
   "title": "Zookeeper Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_up{namespace=\"$nsexporters\"}"
    }
   ]
  },
  {
   "title": "Elasticsearch Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{color=\"red\", namespace=\"$nsexporters\"}==1 or (elasticsearch_cluster_health_status{color=\"green\",namespace=\"$nsexporters\"}==1)+4 or (elasticsearch_cluster_health_status{color=\"yellow\",namespace=\"$nsexporters\"}==1)+22"
    }
   ]
  },
  { "title": "Kong", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Kong status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Routes per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 42 },
   "targets": [
    {}
   ]
  }
 ]
}