apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-leonardo-k8s-resources
  labels:
    {{ .Values.global.sidecar.dashboard }}: "1"
data:
  grafana-dashboard-k8s-resources.json: |-
{{ .Files.Get "conf/grafana-dashboard-k8s-resources.json" | indent 4 }}