apiVersion: v1
kind: Service
metadata:
  name: victoria-service
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8428
      targetPort: http
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: victoria-metrics-single
    app.kubernetes.io/instance: victoria-metrics